/**
 * \file
 *
 * \brief Driver initialization.
 *
 *
 * Copyright (C) 2016 Atmel Corporation. All rights reserved.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 *    Atmel microcontroller product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * \asf_license_stop
 *
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include "twi.h"
#include <system.h>

/* configure pins and initialize registers */
void I2C_0_initialization(void)
{
    PC5_set_dir(
        // <y> Pin direction
        // <id> pad_dir
        // <PORT_DIR_OFF"> Off
        // <PORT_DIR_IN"> In
        // <PORT_DIR_OUT"> Out
        PORT_DIR_OUT);
    PC5_set_level(
        // <y> Initial level
        // <id> pad_initial_level
        // <false"> Low
        // <true"> High
        false);
    PC5_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    PC4_set_dir(
        // <y> Pin direction
        // <id> pad_dir
        // <PORT_DIR_OFF"> Off
        // <PORT_DIR_IN"> In
        // <PORT_DIR_OUT"> Out
        PORT_DIR_OUT);
    PC4_set_level(
        // <y> Initial level
        // <id> pad_initial_level
        // <false"> Low
        // <true"> High
        false);
    PC4_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    I2C_0_init();
}

/* configure pins and initialize registers */
void I2C_1_initialization(void)
{
    //Set these so they don't interfere with main bus until ready.
    PE1_set_dir(
        // <y> Pin direction
        // <id> pad_dir
        // <PORT_DIR_OFF"> Off
        // <PORT_DIR_IN"> In
        // <PORT_DIR_OUT"> Out
        PORT_DIR_IN);
    PE1_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    PE0_set_dir(
        // <y> Pin direction
        // <id> pad_dir
        // <PORT_DIR_OFF"> Off
        // <PORT_DIR_IN"> In
        // <PORT_DIR_OUT"> Out
        PORT_DIR_IN);
    PE0_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    I2C_1_init();
}

void TIMER_0_initialization(void)
{
    TIMER_0_init();
}

void TIMER_1_initialization(void)
{
    TIMER_1_init();
}

void system_init()
{
    mcu_init();
    /* PORT setting on PB6 */
    // Set pin direction to input
    ADDR_IN_set_dir(PORT_DIR_IN);
    ADDR_IN_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    /* PORT setting on PB7 */
    // Set pin direction to input
    MST_set_dir(PORT_DIR_IN);
    MST_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_UP);
    /* PORT setting on PC0 */
    // Set pin direction to output
    SYNC_set_dir(PORT_DIR_IN);
    SYNC_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    /* PORT setting on PC1 */
    // Set pin direction to input
    ADDR_OUT_set_dir(PORT_DIR_IN);
    ADDR_OUT_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    /* PORT setting on PC2 */
    // Set pin direction to output
    XSHUT_set_dir(PORT_DIR_OUT);
    XSHUT_set_level(
        // <y> Initial level
        // <id> pad_initial_level
        // <false"> Low
        // <true"> High
        true);

    /* PORT setting on PC3 */
    // Set pin direction to input
    GPIO1_set_dir(PORT_DIR_IN);

	//Pullups removed on Rev.01c, will still work with Rev.01b and lower boards.
    GPIO1_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_UP);

    /* PORT setting on PD3 */
    // Set pin direction to input
    GND_set_dir(PORT_DIR_IN);
    GND_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    /* PORT setting on PD5 */
    // Set pin direction to input
    GND2_set_dir(PORT_DIR_IN);
    GND2_set_pull_mode(
        // <y> Pull configuration
        // <id> pad_pull_config
        // <PORT_PULL_OFF"> Off
        // <PORT_PULL_UP"> Pull-up
        PORT_PULL_OFF);
    /* PORT setting on PE3 */
    // Set pin direction to output
    LED_set_dir(PORT_DIR_OUT);
    LED_set_level(
        // <y> Initial level
        // <id> pad_initial_level
        // <false"> Low
        // <true"> High
        true);
    sysctrl_init();
    //FLASH_0_init();
    WDT_0_init();
    I2C_0_initialization();
    I2C_1_initialization();
    //TIMER_0_initialization();
    //TIMER_1_initialization();

	UNUSED_set_input();
}
